Fix service status for unprivileged user Resolves: #971776

diff --git a/mariadb-daemonstatus.patch b/mariadb-daemonstatus.patch
--- a/mariadb-daemonstatus.patch
+++ b/mariadb-daemonstatus.patch
@@ -1,6 +1,6 @@
-diff -up mariadb-5.5.30/mysql.init.daemonstatus mariadb-5.5.30/mysql.init
---- mariadb-5.5.30/mysql.init.daemonstatus	2013-05-06 08:23:55.325087367 +0200
-+++ mariadb-5.5.30/mysql.init	2013-05-06 08:26:16.692313766 +0200
+diff -up mariadb-5.5.31/mysql.init.daemonstatus mariadb-5.5.31/mysql.init
+--- mariadb-5.5.31/mysql.init.daemonstatus	2013-06-10 18:59:57.641848042 +0200
++++ mariadb-5.5.31/mysql.init	2013-06-10 19:04:00.082822544 +0200
 @@ -24,7 +24,7 @@
  
  
@@ -10,16 +10,16 @@ diff -up mariadb-5.5.30/mysql.init.daemonstatus mariadb-5.5.30/mysql.init
  
  # Set timeouts here so they can be overridden from /etc/sysconfig/mysqld
  STARTTIMEOUT=120
-@@ -61,12 +61,19 @@ mypidfile="$result"
+@@ -61,19 +61,31 @@ mypidfile="$result"
  start(){
      [ -x $exec ] || exit 5
      # check to see if it's already running
 +    MYSQLDRUNNING=0
 +    if [ -f "$mypidfile" ]; then
-+        MYSQLPID=`cat "$mypidfile"`
-+        if [ -n "$MYSQLPID" ]; then
-+            /bin/kill -0 "$MYSQLPID" && MYSQLDRUNNING=1
-+        fi
++        MYSQLPID=`cat "$mypidfile" 2>/dev/null`
++	if [ -n "$MYSQLPID" ] && [ -d "/proc/$MYSQLPID" ] ; then
++	    MYSQLDRUNNING=1
++	fi
 +    fi
      RESPONSE=`/usr/bin/mysqladmin --socket="$socketfile" --user=UNKNOWN_MYSQL_USER ping 2>&1`
 -    if [ $? = 0 ]; then
@@ -32,7 +32,20 @@ diff -up mariadb-5.5.30/mysql.init.daemonstatus mariadb-5.5.30/mysql.init
      then
  	# already running, do nothing
  	action $"Starting $prog: " /bin/true
-@@ -103,6 +110,11 @@ start(){
+ 	ret=0
+     else
+     	# prepare for start
+-	touch "$errlogfile"
++	touch "$errlogfile" 2>/dev/null
++	if [ $? -ne 0 ]; then
++	     # failed to touch log file, probably insufficient permissions
++	     action $"Starting $prog: " /bin/false
++	     return 4
++	fi
+ 	chown mysql:mysql "$errlogfile" 
+ 	chmod 0640 "$errlogfile"
+ 	[ -x /sbin/restorecon ] && /sbin/restorecon "$errlogfile"
+@@ -103,6 +115,11 @@ start(){
  	# and some users might prefer to configure logging to syslog.)
  	# Note: set --basedir to prevent probes that might trigger SELinux
  	# alarms, per bug #547485
@@ -44,7 +57,34 @@ diff -up mariadb-5.5.30/mysql.init.daemonstatus mariadb-5.5.30/mysql.init
  	$exec   --datadir="$datadir" --socket="$socketfile" \
  		--pid-file="$mypidfile" \
  		--basedir=/usr --user=mysql >/dev/null 2>&1 &
-@@ -221,7 +233,7 @@ case "$1" in
+@@ -142,6 +159,7 @@ start(){
+ 	fi
+ 	if [ $ret -eq 0 ]; then
+ 	    action $"Starting $prog: " /bin/true
++	    chmod o+r $mypidfile >/dev/null 2>&1
+ 	    touch $lockfile
+ 	else
+ 	    action $"Starting $prog: " /bin/false
+@@ -156,7 +174,7 @@ stop(){
+ 	    action $"Stopping $prog: " /bin/true
+ 	    return 0
+ 	fi
+-	MYSQLPID=`cat "$mypidfile"`
++	MYSQLPID=`cat "$mypidfile" 2>/dev/null`
+ 	if [ -n "$MYSQLPID" ]; then
+ 	    /bin/kill "$MYSQLPID" >/dev/null 2>&1
+ 	    ret=$?
+@@ -177,7 +195,9 @@ stop(){
+ 		    action $"Stopping $prog: " /bin/true
+ 		fi
+ 	    else
++		# kill command failed, probably insufficient permissions
+ 		action $"Stopping $prog: " /bin/false
++		ret=4
+ 	    fi
+ 	else
+ 	    # failed to read pidfile, probably insufficient permissions
+@@ -221,7 +241,7 @@ case "$1" in
      stop
      ;;
    status)
